POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Evento musical",
    "details": "um evento para quem é apaixonado por musical",
    "maximumAttendees": 1
}


###

POST http://localhost:3333/events/4e198939-c40a-4b84-a02a-8f2ee8b75b66/attendees
Content-Type: application/json

{
    "name": "Fabiola Nascimento",
    "email": "fabiola7@email.com"
}

###

GET http://localhost:3333/events/4e198939-c40a-4b84-a02a-8f2ee8b75b66

###

GET http://localhost:3333/attendees/0X-0qxj/badge

###

GET http://localhost:3333/attendees/07-RlAF/check-in

###

GET http://localhost:3333/events/4e198939-c40a-4b84-a02a-8f2ee8b75b66/attendees